services:
    bestnid_user.registration.form.type:
        class: Bestnid\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: bestnid_user_registration }